default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: matsushita
  password: matsushita
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: tentai_app_development

test:
  <<: *default
  database: tentai_app_test

production:
  <<: *default
  database: tentai_app_production